version: '3.8'
services:
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  app:
    build: .
    command: python3 -m uvicorn main:app --reload --host 0.0.0.0 --port 80
    depends_on:
      - postgres
